### DISCUSSION TITLE
How to convert standard vias in microvia in HFSS 3D Layout

### DISCUSSION THREAD

**Discussion by amichel0205** [ansys/pyaedt#4111] [Show and tell]
You will find below a script example on how to convert standard via to µvia. 

This is a pyedb script and will create a an HFSS 3D Layout project from an original aedb folder.
Before to run the script ensure the original project is not loaded in AEDT.

PyAEDT version V0.9
 or latter need to be used

Copy and paste the script in a file named ConverToMicrovia.py.

```python
# PyAEDT version V0.9 and PyEDB version 0.21 or latter need to be used
from pyaedt import Hfss3dLayout
import pyedb
import os
import toml

# Setting of toml configuration file used to set a dictionary
res = toml.load(r'C:\Users\amichel\Desktop\Documents\Ansoft\PersonalLib\configfile_microvia.toml')

# Path to the aedb directory to convert
aedbpathin = res['aedb']['aedbpathin']
# Path to where the new aedb directory will be created
aedbpathout = res['aedb']['aedbpathout']
# Name of the aedn directory to convert
aedbfilein = 'PCIE_RX_HFSS_5Ghz_20GHZ.aedb'
# Name of the new created aedb directory
aedbfileout = 'PCIE_RX_HFSS_5Ghz_20GHZ_uvia_45deg.aedb'
# List of padstack for which instance via will be converted to micro-via
pdsk_list = res['setup']['pdsk_list']
# Hole wall angle from start pad to end pad
laser_angle = res['setup']['laser_angle']
# True convert only signal via, False convert signal and GND via
only_sig_via =res['setup']['only_sig_via']
# Version of AEDT to be used
version = res['aedt']['version']


# name of the padstack mapped with standard via to convert to µvia
# All via instances mapped with padstack name from pdsk_list will be converted,
# it is mandatory to enter padstack name in lower case(whatever case is used in AEDT)

aedbinput = os.path.join(aedbpathin, aedbfilein)
aedboutput = os.path.join(aedbpathout, aedbfileout)

if not os.path.exists(aedboutput):
        print("Create a new project with standard via converted to micro-vias")
        edb = pyedb.Edb(edbpath=aedbinput, edbversion=version)

        edb.save_edb_as(aedboutput)

        for k_pdsk in pdsk_list:
            for k, v in edb.padstacks.definitions.items():
                if k.lower() == k_pdsk:
                    v.convert_to_3d_microvias(convert_only_signal_vias=only_sig_via, hole_wall_angle=laser_angle,
                                              delete_padstack_def=False)
                    print(k, "Converted to microvia")

        edb.save_edb()
        edb.close_edb()

        hfss = Hfss3dLayout(specified_version=version, projectname=aedboutput)

        hfss.release_desktop(close_projects=False, close_desktop=False)
else:
    print("aedb folder " + aedboutput + " already exist convert micro-via stopped")

``` 
This python script will be driven from a toml file named configfile_microvia.toml  to be placed in PersonalLib.
toml file below need to be used.
Copy and paste the toml file below in a file named "configfile_microvia.toml" and place it in AEDT PersonalLib(it is mandatory to respect the name and location of toml file)

```toml
[aedb]
# Path to the aedb directory to convert
aedbpathin = "D:\\Data\\siverse\\uvia"
# Path to where the new aedb directory will be created
aedbpathout = "D:\\Data\\siverse\\uvia\\3DVia"
# Name of the aedn directory to convert
aedbfilein = "PCIE_RX_HFSS_5Ghz_20GHZ.aedb"
# Name of the new created aedb directory
aedbfileout = "PCIE_RX_HFSS_5Ghz_20GHZ_uvia_45deg.aedb"

[aedt]
# Version of AEDT to be used "2023.2" for 2023R2, "2024.1" for 2024R1
version = "2024.1"

[setup]
# List of padstack for which instance via will be converted to micro-via
pdsk_list = ["v40h20-2", "v40h15-3", "v40h15-4"]
# Hole wall angle from start pad to end pad
laser_angle = 45
# True convert only signal via, False convert signal and GND via
only_sig_via = true
```
Unzip the file below in the directory of choice(this can be used to test the script)
[PCIE_RX_HFSS_5Ghz_20GHZ.aedb.zip](https://github.com/user-attachments/files/16353011/PCIE_RX_HFSS_5Ghz_20GHZ.aedb.zip)

To run the script:

- Ensure last version of PyAEDT is installed ( PyAEDT version V0.9 latter need to be used)
- Load AEDT
- Click on Tab "Automation"
![image](https://github.com/user-attachments/assets/a473c6ad-b37f-4232-aa74-323b79b5667e)
- Click on icon "Extension Manager
![image](https://github.com/user-attachments/assets/de91095b-156e-4d7f-b796-4ef0d701069f)
- "Extension Managaer" window popup. Click on Project
![image](https://github.com/user-attachments/assets/d64907ac-dafc-4641-be5b-2b0c8c8b4b4b)
- "Project" window popup
![image](https://github.com/user-attachments/assets/b3998711-8676-4de9-84bd-29d27003fa52)
- In "Extension" select "Custom"(it should be already selected)
- In "Enter script path:" enter the full path of the python script you previously copied(eg. C:\Data\pyaedt\scripts\ConvertToMicrovia.py). Ensure no quotes are copied with the path
- In "Enter toolkit name:" enter name of the toolkit (eg. "Convert to Uvias")
![image](https://github.com/user-attachments/assets/9f6f5250-4683-40f4-b4b1-bed843b89862)
- click "Install"
- Close windows "Project" and "Extension Manager"
- Click "File Close"
![image](https://github.com/user-attachments/assets/5b72099d-d3b1-43a5-a8e1-0b562beaff00)
- Click "File New"
![image](https://github.com/user-attachments/assets/6f4546f8-dafd-4137-9313-61202f216560)
- The new icon "Convert to Uvias" appears

Before to run "Convert to Uvias" script ensure the correct information are set in "configfile_microvia.toml":

- Path to the aedb directory to convert
- Path to where the new aedb directory will be created
- Name of the aedb directory to convert
- Name of the new created aedb directory
- Version of AEDT to be used "2023.2" for 2023R2, "2024.1" for 2024R1(in the copied toml file 2024.1)
- List of padstack for which instance via will be converted to micro-via(all via instance mapped to padstack in the list will be converted)
- laser_angle: Hole wall angle from start pad to end pad
![image](https://github.com/user-attachments/assets/b90633dd-d56f-4f85-900d-92d05c7ce0f1)
- only_sig_via: True convert only signal via, False convert signal and GND via

More information on function convert_to_3d_microvias by clicking the link below:

[https://aedt.docs.pyansys.com/version/stable/EDBAPI/_autosummary/pyaedt.edb_core.edb_data.padstacks_data.EDBPadstack.convert_to_3d_microvias.html](url)

> [!CAUTION]
>Warning with using function convert_to_3d_microvias:
>
>- OverrideHoleDiameter Via property not supported yet: User will have to manually uncheck this option for all standard via converted to >µvia
>- Using option "convert_only_signal_vias=False" when same padstack definition is mapped to signal_via and non-signal via is not supported. The results is all non signal_via mapped on the padstack used to convert via to µvia will have hole diameter set to 0. This will be corrected in further release of pyaedt.

View of original design:
![image](https://github.com/ansys/pyaedt/assets/119294121/05b1abeb-5164-4fcb-822d-7bf7ca05eb61)

View of design with via converted to µvia with angle of laser penetration = 15 degrees
![image](https://github.com/ansys/pyaedt/assets/119294121/ebf51880-daad-44a9-a5b0-924d1a0e8243)
